let suggestions = [
    "Pecan Ricotta",
"Coconut Yoghurt Cake",
"Simply Guacamole",
"Strawberry Bruschetta",
 "Deviled Eggs",
 "Berry Oats",
 "Brunch Enchiladas",
"Mushroom Spinach Omelete",
"Breakfast cups",    
"Oyakodon",
 "One-pot Chicken Chow Mein",
 "Sweet and Sour Chicken",
 "General Tsos Recipe",
 "Vegetable Gyoza",
 "Chicken pho soup",
 "Carrot Cheesecake",
 "Tiramisu cake",
  "Instant Pot Cake",
   "Cherry ice Cream",
 "Almond Cinnamon Cookies",
  "Orange Dream Punch",
   "Lemonade",
 "Peanut Butter Banana Smoothie",
  "Cappuccino Cooler",
   "Mocha",
   "Mango Falooda",
"Rasam",
"Kadlebele Vade",
 "Murruku",
  "Coconut Rice",
  "Puliyogare",
"Easy Tuscan Chicken",
 "Rosemary Mushroom Risotto",
 "Caprese Chicken",
 "Calzone",
 "Muffuletta Sandwich", 
"Cabbage Sabzi",
 "Aloo Paratha",
 "Paneer Sabzi",
  "Palak Paneer",
 "Dal Makhani"
];